apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
    component: {{ .Release.Namespace }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Release.Namespace }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Release.Namespace }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: {{ .Values.service.port }}
        command: ["/bin/sh"]
        args: ["-c","python manage.py migrate && python manage.py runserver 0.0.0.0:3003"]
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value }}
        {{- end }}
      volumes:
        - name: {{ .Values.volumes.name }}

